### YamlMime:ManagedReference
items:
- uid: ClaySharp.Interop.SharedElementConfig
  commentId: T:ClaySharp.Interop.SharedElementConfig
  id: SharedElementConfig
  parent: ClaySharp.Interop
  children:
  - ClaySharp.Interop.SharedElementConfig.BackgroundColor
  - ClaySharp.Interop.SharedElementConfig.CornerRadius
  - ClaySharp.Interop.SharedElementConfig.UserData
  langs:
  - csharp
  - vb
  name: SharedElementConfig
  nameWithType: SharedElementConfig
  fullName: ClaySharp.Interop.SharedElementConfig
  type: Struct
  source:
    id: SharedElementConfig
    path: C:\Users\user\source\repos\ClaySharp\BlackHook.ClaySharp\Interop\ClayTypes.cs
    startLine: 929
  assemblies:
  - BlackHook.ClaySharp
  namespace: ClaySharp.Interop
  summary: Represents style settings that are shared across multiple layout nodes.
  example: []
  syntax:
    content: public struct SharedElementConfig
    content.vb: Public Structure SharedElementConfig
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: ClaySharp.Interop.SharedElementConfig.BackgroundColor
  commentId: F:ClaySharp.Interop.SharedElementConfig.BackgroundColor
  id: BackgroundColor
  parent: ClaySharp.Interop.SharedElementConfig
  langs:
  - csharp
  - vb
  name: BackgroundColor
  nameWithType: SharedElementConfig.BackgroundColor
  fullName: ClaySharp.Interop.SharedElementConfig.BackgroundColor
  type: Field
  source:
    id: BackgroundColor
    path: C:\Users\user\source\repos\ClaySharp\BlackHook.ClaySharp\Interop\ClayTypes.cs
    startLine: 933
  assemblies:
  - BlackHook.ClaySharp
  namespace: ClaySharp.Interop
  summary: Shared solid background fill color.
  example: []
  syntax:
    content: public Color BackgroundColor
    return:
      type: ClaySharp.Interop.Color
    content.vb: Public BackgroundColor As Color
- uid: ClaySharp.Interop.SharedElementConfig.CornerRadius
  commentId: F:ClaySharp.Interop.SharedElementConfig.CornerRadius
  id: CornerRadius
  parent: ClaySharp.Interop.SharedElementConfig
  langs:
  - csharp
  - vb
  name: CornerRadius
  nameWithType: SharedElementConfig.CornerRadius
  fullName: ClaySharp.Interop.SharedElementConfig.CornerRadius
  type: Field
  source:
    id: CornerRadius
    path: C:\Users\user\source\repos\ClaySharp\BlackHook.ClaySharp\Interop\ClayTypes.cs
    startLine: 936
  assemblies:
  - BlackHook.ClaySharp
  namespace: ClaySharp.Interop
  summary: Shared corner rounding details.
  example: []
  syntax:
    content: public CornerRadius CornerRadius
    return:
      type: ClaySharp.Interop.CornerRadius
    content.vb: Public CornerRadius As CornerRadius
- uid: ClaySharp.Interop.SharedElementConfig.UserData
  commentId: F:ClaySharp.Interop.SharedElementConfig.UserData
  id: UserData
  parent: ClaySharp.Interop.SharedElementConfig
  langs:
  - csharp
  - vb
  name: UserData
  nameWithType: SharedElementConfig.UserData
  fullName: ClaySharp.Interop.SharedElementConfig.UserData
  type: Field
  source:
    id: UserData
    path: C:\Users\user\source\repos\ClaySharp\BlackHook.ClaySharp\Interop\ClayTypes.cs
    startLine: 939
  assemblies:
  - BlackHook.ClaySharp
  namespace: ClaySharp.Interop
  summary: Shared custom user-defined data pointer.
  example: []
  syntax:
    content: public nint UserData
    return:
      type: System.IntPtr
    content.vb: Public UserData As IntPtr
references:
- uid: ClaySharp.Interop
  commentId: N:ClaySharp.Interop
  href: ClaySharp.html
  name: ClaySharp.Interop
  nameWithType: ClaySharp.Interop
  fullName: ClaySharp.Interop
  spec.csharp:
  - uid: ClaySharp
    name: ClaySharp
    href: ClaySharp.html
  - name: .
  - uid: ClaySharp.Interop
    name: Interop
    href: ClaySharp.Interop.html
  spec.vb:
  - uid: ClaySharp
    name: ClaySharp
    href: ClaySharp.html
  - name: .
  - uid: ClaySharp.Interop
    name: Interop
    href: ClaySharp.Interop.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ClaySharp.Interop.Color
  commentId: T:ClaySharp.Interop.Color
  parent: ClaySharp.Interop
  href: ClaySharp.Interop.Color.html
  name: Color
  nameWithType: Color
  fullName: ClaySharp.Interop.Color
- uid: ClaySharp.Interop.CornerRadius
  commentId: T:ClaySharp.Interop.CornerRadius
  parent: ClaySharp.Interop
  href: ClaySharp.Interop.CornerRadius.html
  name: CornerRadius
  nameWithType: CornerRadius
  fullName: ClaySharp.Interop.CornerRadius
- uid: System.IntPtr
  commentId: T:System.IntPtr
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.intptr
  name: nint
  nameWithType: nint
  fullName: nint
  nameWithType.vb: IntPtr
  fullName.vb: System.IntPtr
  name.vb: IntPtr
