### YamlMime:ManagedReference
items:
- uid: ClaySharp.Interop.LayoutConfigArray
  commentId: T:ClaySharp.Interop.LayoutConfigArray
  id: LayoutConfigArray
  parent: ClaySharp.Interop
  children:
  - ClaySharp.Interop.LayoutConfigArray.Capacity
  - ClaySharp.Interop.LayoutConfigArray.InternalArray
  - ClaySharp.Interop.LayoutConfigArray.Length
  langs:
  - csharp
  - vb
  name: LayoutConfigArray
  nameWithType: LayoutConfigArray
  fullName: ClaySharp.Interop.LayoutConfigArray
  type: Struct
  source:
    id: LayoutConfigArray
    path: C:\Users\user\source\repos\ClaySharp\BlackHook.ClaySharp\Interop\ClayTypes.cs
    startLine: 763
  assemblies:
  - BlackHook.ClaySharp
  namespace: ClaySharp.Interop
  summary: Unmanaged array wrapper for <xref href="ClaySharp.Interop.LayoutConfig" data-throw-if-not-resolved="false"></xref> elements.
  example: []
  syntax:
    content: public struct LayoutConfigArray
    content.vb: Public Structure LayoutConfigArray
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: ClaySharp.Interop.LayoutConfigArray.Capacity
  commentId: F:ClaySharp.Interop.LayoutConfigArray.Capacity
  id: Capacity
  parent: ClaySharp.Interop.LayoutConfigArray
  langs:
  - csharp
  - vb
  name: Capacity
  nameWithType: LayoutConfigArray.Capacity
  fullName: ClaySharp.Interop.LayoutConfigArray.Capacity
  type: Field
  source:
    id: Capacity
    path: C:\Users\user\source\repos\ClaySharp\BlackHook.ClaySharp\Interop\ClayTypes.cs
    startLine: 767
  assemblies:
  - BlackHook.ClaySharp
  namespace: ClaySharp.Interop
  summary: The capacity of the array.
  example: []
  syntax:
    content: public int Capacity
    return:
      type: System.Int32
    content.vb: Public Capacity As Integer
- uid: ClaySharp.Interop.LayoutConfigArray.Length
  commentId: F:ClaySharp.Interop.LayoutConfigArray.Length
  id: Length
  parent: ClaySharp.Interop.LayoutConfigArray
  langs:
  - csharp
  - vb
  name: Length
  nameWithType: LayoutConfigArray.Length
  fullName: ClaySharp.Interop.LayoutConfigArray.Length
  type: Field
  source:
    id: Length
    path: C:\Users\user\source\repos\ClaySharp\BlackHook.ClaySharp\Interop\ClayTypes.cs
    startLine: 769
  assemblies:
  - BlackHook.ClaySharp
  namespace: ClaySharp.Interop
  summary: The active length of the array.
  example: []
  syntax:
    content: public int Length
    return:
      type: System.Int32
    content.vb: Public Length As Integer
- uid: ClaySharp.Interop.LayoutConfigArray.InternalArray
  commentId: F:ClaySharp.Interop.LayoutConfigArray.InternalArray
  id: InternalArray
  parent: ClaySharp.Interop.LayoutConfigArray
  langs:
  - csharp
  - vb
  name: InternalArray
  nameWithType: LayoutConfigArray.InternalArray
  fullName: ClaySharp.Interop.LayoutConfigArray.InternalArray
  type: Field
  source:
    id: InternalArray
    path: C:\Users\user\source\repos\ClaySharp\BlackHook.ClaySharp\Interop\ClayTypes.cs
    startLine: 771
  assemblies:
  - BlackHook.ClaySharp
  namespace: ClaySharp.Interop
  summary: A raw pointer to the unmanaged array of configs.
  example: []
  syntax:
    content: public LayoutConfig* InternalArray
    return:
      type: ClaySharp.Interop.LayoutConfig*
    content.vb: Public InternalArray As LayoutConfig*
references:
- uid: ClaySharp.Interop.LayoutConfig
  commentId: T:ClaySharp.Interop.LayoutConfig
  parent: ClaySharp.Interop
  href: ClaySharp.Interop.LayoutConfig.html
  name: LayoutConfig
  nameWithType: LayoutConfig
  fullName: ClaySharp.Interop.LayoutConfig
- uid: ClaySharp.Interop
  commentId: N:ClaySharp.Interop
  href: ClaySharp.html
  name: ClaySharp.Interop
  nameWithType: ClaySharp.Interop
  fullName: ClaySharp.Interop
  spec.csharp:
  - uid: ClaySharp
    name: ClaySharp
    href: ClaySharp.html
  - name: .
  - uid: ClaySharp.Interop
    name: Interop
    href: ClaySharp.Interop.html
  spec.vb:
  - uid: ClaySharp
    name: ClaySharp
    href: ClaySharp.html
  - name: .
  - uid: ClaySharp.Interop
    name: Interop
    href: ClaySharp.Interop.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: ClaySharp.Interop.LayoutConfig*
  isExternal: true
  href: ClaySharp.Interop.LayoutConfig.html
  name: LayoutConfig*
  nameWithType: LayoutConfig*
  fullName: ClaySharp.Interop.LayoutConfig*
  spec.csharp:
  - uid: ClaySharp.Interop.LayoutConfig
    name: LayoutConfig
    href: ClaySharp.Interop.LayoutConfig.html
  - name: '*'
  spec.vb:
  - uid: ClaySharp.Interop.LayoutConfig
    name: LayoutConfig
    href: ClaySharp.Interop.LayoutConfig.html
  - name: '*'
