### YamlMime:ManagedReference
items:
- uid: ClaySharp.Interop.LayoutConfig
  commentId: T:ClaySharp.Interop.LayoutConfig
  id: LayoutConfig
  parent: ClaySharp.Interop
  children:
  - ClaySharp.Interop.LayoutConfig.ChildAlignment
  - ClaySharp.Interop.LayoutConfig.ChildGap
  - ClaySharp.Interop.LayoutConfig.LayoutDirection
  - ClaySharp.Interop.LayoutConfig.Padding
  - ClaySharp.Interop.LayoutConfig.Sizing
  langs:
  - csharp
  - vb
  name: LayoutConfig
  nameWithType: LayoutConfig
  fullName: ClaySharp.Interop.LayoutConfig
  type: Struct
  source:
    id: LayoutConfig
    path: C:\Users\user\source\repos\ClaySharp\BlackHook.ClaySharp\Interop\ClayTypes.cs
    startLine: 259
  assemblies:
  - BlackHook.ClaySharp
  namespace: ClaySharp.Interop
  summary: Defines general layout configurations for element arrangement, spacing, and sizing.
  example: []
  syntax:
    content: public struct LayoutConfig
    content.vb: Public Structure LayoutConfig
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: ClaySharp.Interop.LayoutConfig.Sizing
  commentId: F:ClaySharp.Interop.LayoutConfig.Sizing
  id: Sizing
  parent: ClaySharp.Interop.LayoutConfig
  langs:
  - csharp
  - vb
  name: Sizing
  nameWithType: LayoutConfig.Sizing
  fullName: ClaySharp.Interop.LayoutConfig.Sizing
  type: Field
  source:
    id: Sizing
    path: C:\Users\user\source\repos\ClaySharp\BlackHook.ClaySharp\Interop\ClayTypes.cs
    startLine: 263
  assemblies:
  - BlackHook.ClaySharp
  namespace: ClaySharp.Interop
  summary: Axis sizing rules.
  example: []
  syntax:
    content: public Sizing Sizing
    return:
      type: ClaySharp.Interop.Sizing
    content.vb: Public Sizing As Sizing
- uid: ClaySharp.Interop.LayoutConfig.Padding
  commentId: F:ClaySharp.Interop.LayoutConfig.Padding
  id: Padding
  parent: ClaySharp.Interop.LayoutConfig
  langs:
  - csharp
  - vb
  name: Padding
  nameWithType: LayoutConfig.Padding
  fullName: ClaySharp.Interop.LayoutConfig.Padding
  type: Field
  source:
    id: Padding
    path: C:\Users\user\source\repos\ClaySharp\BlackHook.ClaySharp\Interop\ClayTypes.cs
    startLine: 266
  assemblies:
  - BlackHook.ClaySharp
  namespace: ClaySharp.Interop
  summary: Interior boundary padding values.
  example: []
  syntax:
    content: public Padding Padding
    return:
      type: ClaySharp.Interop.Padding
    content.vb: Public Padding As Padding
- uid: ClaySharp.Interop.LayoutConfig.ChildGap
  commentId: F:ClaySharp.Interop.LayoutConfig.ChildGap
  id: ChildGap
  parent: ClaySharp.Interop.LayoutConfig
  langs:
  - csharp
  - vb
  name: ChildGap
  nameWithType: LayoutConfig.ChildGap
  fullName: ClaySharp.Interop.LayoutConfig.ChildGap
  type: Field
  source:
    id: ChildGap
    path: C:\Users\user\source\repos\ClaySharp\BlackHook.ClaySharp\Interop\ClayTypes.cs
    startLine: 269
  assemblies:
  - BlackHook.ClaySharp
  namespace: ClaySharp.Interop
  summary: Spaced gap distance in pixels between sequential child elements.
  example: []
  syntax:
    content: public ushort ChildGap
    return:
      type: System.UInt16
    content.vb: Public ChildGap As UShort
- uid: ClaySharp.Interop.LayoutConfig.ChildAlignment
  commentId: F:ClaySharp.Interop.LayoutConfig.ChildAlignment
  id: ChildAlignment
  parent: ClaySharp.Interop.LayoutConfig
  langs:
  - csharp
  - vb
  name: ChildAlignment
  nameWithType: LayoutConfig.ChildAlignment
  fullName: ClaySharp.Interop.LayoutConfig.ChildAlignment
  type: Field
  source:
    id: ChildAlignment
    path: C:\Users\user\source\repos\ClaySharp\BlackHook.ClaySharp\Interop\ClayTypes.cs
    startLine: 272
  assemblies:
  - BlackHook.ClaySharp
  namespace: ClaySharp.Interop
  summary: Child alignment placement properties.
  example: []
  syntax:
    content: public ChildAlignment ChildAlignment
    return:
      type: ClaySharp.Interop.ChildAlignment
    content.vb: Public ChildAlignment As ChildAlignment
- uid: ClaySharp.Interop.LayoutConfig.LayoutDirection
  commentId: F:ClaySharp.Interop.LayoutConfig.LayoutDirection
  id: LayoutDirection
  parent: ClaySharp.Interop.LayoutConfig
  langs:
  - csharp
  - vb
  name: LayoutDirection
  nameWithType: LayoutConfig.LayoutDirection
  fullName: ClaySharp.Interop.LayoutConfig.LayoutDirection
  type: Field
  source:
    id: LayoutDirection
    path: C:\Users\user\source\repos\ClaySharp\BlackHook.ClaySharp\Interop\ClayTypes.cs
    startLine: 275
  assemblies:
  - BlackHook.ClaySharp
  namespace: ClaySharp.Interop
  summary: Direction direction along which elements are appended (horizontal or vertical).
  example: []
  syntax:
    content: public LayoutDirection LayoutDirection
    return:
      type: ClaySharp.Interop.LayoutDirection
    content.vb: Public LayoutDirection As LayoutDirection
references:
- uid: ClaySharp.Interop
  commentId: N:ClaySharp.Interop
  href: ClaySharp.html
  name: ClaySharp.Interop
  nameWithType: ClaySharp.Interop
  fullName: ClaySharp.Interop
  spec.csharp:
  - uid: ClaySharp
    name: ClaySharp
    href: ClaySharp.html
  - name: .
  - uid: ClaySharp.Interop
    name: Interop
    href: ClaySharp.Interop.html
  spec.vb:
  - uid: ClaySharp
    name: ClaySharp
    href: ClaySharp.html
  - name: .
  - uid: ClaySharp.Interop
    name: Interop
    href: ClaySharp.Interop.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ClaySharp.Interop.Sizing
  commentId: T:ClaySharp.Interop.Sizing
  parent: ClaySharp.Interop
  href: ClaySharp.Interop.Sizing.html
  name: Sizing
  nameWithType: Sizing
  fullName: ClaySharp.Interop.Sizing
- uid: ClaySharp.Interop.Padding
  commentId: T:ClaySharp.Interop.Padding
  parent: ClaySharp.Interop
  href: ClaySharp.Interop.Padding.html
  name: Padding
  nameWithType: Padding
  fullName: ClaySharp.Interop.Padding
- uid: System.UInt16
  commentId: T:System.UInt16
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.uint16
  name: ushort
  nameWithType: ushort
  fullName: ushort
  nameWithType.vb: UShort
  fullName.vb: UShort
  name.vb: UShort
- uid: ClaySharp.Interop.ChildAlignment
  commentId: T:ClaySharp.Interop.ChildAlignment
  parent: ClaySharp.Interop
  href: ClaySharp.Interop.ChildAlignment.html
  name: ChildAlignment
  nameWithType: ChildAlignment
  fullName: ClaySharp.Interop.ChildAlignment
- uid: ClaySharp.Interop.LayoutDirection
  commentId: T:ClaySharp.Interop.LayoutDirection
  parent: ClaySharp.Interop
  href: ClaySharp.Interop.LayoutDirection.html
  name: LayoutDirection
  nameWithType: LayoutDirection
  fullName: ClaySharp.Interop.LayoutDirection
